### ISSUE TITLE
use -include-stdlib error

### ISSUE THREAD

**Issue by wangcheng711** [google/godepq#24] opened 2017-12-25 13:19 UTC
godepq -from github.com/go-sql-driver/mysql -include-stdlib

output
Error: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
        /usr/local/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOROOT)
        /home/golang/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOPATH)

**Comment by dmitshur** [comment] 2017-12-26 06:51
For reference, `github.com/go-sql-driver/mysql` imports `crypto/tls`, which in turn [does import](https://godoc.org/crypto/tls?imports) `golang_org/x/crypto/chacha20poly1305`. However, that package is only available via in the vendor directory at $GOROOT/src/vendor.

It seems `godepq` isn't able to resolve it for some reason.

Did you build the `godepq` binary with a recent version of Go?

**Comment by wangcheng711** [comment] 2018-01-04 02:57
golang@golang-pc:/usr/local/go/src/vendor$ go version
go version go1.9.2 linux/amd64

golang@golang-pc:/usr/local/go/src/vendor$ ll
总用量 12
drwxr-xr-x  3 root root 4096 10月 26 02:34 ./
drwxr-xr-x 46 root root 4096 10月 26 02:34 ../
drwxr-xr-x  3 root root 4096 10月 26 02:34 golang_org/
golang@golang-pc:/usr/local/go/src/vendor$ godepq -from github.com/go-sql-driver/mysql -include-stdlib
Packages:
  github.com/go-sql-driver/mysql
  net/url
  database/sql
  log
  crypto/tls
  vendor/golang_org/x/crypto/chacha20poly1305
  crypto/x509
  container/list
  crypto/hmac
  vendor/golang_org/x/crypto/curve25519
  crypto/rc4
  database/sql/driver
  crypto/ecdsa
  crypto/des
  encoding/hex
  vendor/golang_org/x/crypto/poly1305
  crypto/sha256
  crypto/x509/pkix
  crypto/md5
  crypto/dsa
  crypto/rsa
  encoding/pem
  io/ioutil
  crypto/sha1
  net
  vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
  encoding/asn1
  encoding/base64
  path/filepath
  crypto/sha512
  crypto/elliptic
  internal/nettrace
  context
  internal/singleflight
  crypto/rand
  internal/syscall/unix
  sort
  crypto
  bufio
  math/big
  crypto/aes
  math/rand
  crypto/internal/cipherhw
  math/bits
  bytes
  hash
  crypto/cipher
  encoding/binary
  strings
  fmt
  crypto/subtle
  os
  reflect
  internal/poll
  unicode
  strconv
  time
  io
  math
  unicode/utf8
  internal/cpu
  errors
  syscall
  sync
  runtime
  sync/atomic
  internal/race
  runtime/internal/atomic
  runtime/internal/sys
  unsafe

in other path its not work.

golang@golang-pc:/usr/local/go/src$ godepq -from github.com/go-sql-driver/mysql -include-stdlib
Error: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
	/usr/local/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOROOT)
	/home/golang/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOPATH)
golang@golang-pc:/usr/local/go/src$

**Comment by tallclair** [comment] 2019-04-22 16:32
I think this is a duplicate of https://github.com/google/godepq/issues/26

**Closed as completed by tallclair** 2019-04-22 16:32 UTC
